apiVersion: v1
kind: Secret
metadata:
  name: datasource-credentials
  labels:
    {{- include "homework-chart.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.secrets.username }}
  password: {{ .Values.secrets.password }}
